Feat: show singular block, insert variables, upgrade single post type…
elightup/slim-seo pull request #146
Opened 2024-07-05 10:51 UTC by nhatrangnet

… page

2024-07-05 23:35 UTC, rilwis requested changes

2024-07-05 23:35 UTC, rilwis commented on js/post-types/components/PostType.js
> +			label={ sprintf( __( 'Singular %s page', 'slim-seo' ), postType.labels.singular_name ) }
Để `postType.labels.singular_name.toLowerCase()` nhé.

2024-07-05 23:35 UTC, rilwis commented on src/Settings/PostTypes.php
> +			'methods'             => \WP_REST_Server::READABLE,
Không cần gạch `\`.

2024-07-12 03:22 UTC, rilwis requested changes

2024-07-12 03:22 UTC, rilwis commented on src/MetaTags/Settings/Base.php
> +		$data['canonical']      = sanitize_text_field( $data['canonical'] );
Tại sao lại thay đổi hàm escape chỗ này vậy? Nó phải là URL chứ?

2024-07-12 03:22 UTC, rilwis commented on src/MetaTags/Data.php
> +use SlimSEO\Breadcrumbs;
Bỏ `use` không dùng đi

2024-07-12 03:22 UTC, rilwis commented on src/MetaTags/Image.php
> +	private function get_from_settings(): array {
Báo lỗi nè, nếu điều kiện `if` ko thoả mãn thì giá trị trả về sẽ ko có gì, ko phù hợp với type hint là `array`. E phải đảm bảo trường hợp đó trả về `[]`.

2024-07-12 04:47 UTC, nhatrangnet commented on src/MetaTags/Settings/Base.php
> +		$data['canonical']      = sanitize_text_field( $data['canonical'] );
@rilwis bởi vì mình có thể setup nó là {{ post.url }} nên nó escape thấy không đúng nữa anh.

2024-07-17 08:39 UTC, rilwis requested changes

2024-07-17 08:39 UTC, rilwis commented on src/MetaTags/Title.php
> +		}
Thiếu `return` cho trường hợp chung.

2024-07-17 08:39 UTC, rilwis commented on src/MetaTags/Description.php
> +		if ( isset( $option[ $post_type ]['description'] ) ) {
Dùng `! empty` nhé.

2024-07-17 08:39 UTC, rilwis commented on src/MetaTags/CanonicalUrl.php
> +		$url = Helper::render( $url );
Thống nhất như title & description là apply filters trước, sau đó chạy render nhé.

2024-07-17 08:39 UTC, rilwis commented on src/MetaTags/Image.php
> +			return $this->get_from_settings();
Logic chỗ này là lấy theo thứ tự:
- post meta
- settings
- thumbnail
- content

Nên e viết lại theo hướng đó cho clear nhé. Tham khảo bên description ấy.

2024-07-17 08:39 UTC, rilwis commented on src/MetaTags/Image.php
> +		}
E test lại với case người ta điền meta value là `https://domain.com/{{ post.slug }}/thumbnail.jpg` xem PHP nó validate URL ko nhé. Ý a là khi dùng variables trong URL thì lệnh `if` này chạy đúng ko nhé.

2024-07-17 08:39 UTC, rilwis commented on src/MetaTags/Image.php
> +	private function get_from_post_meta( $meta_value ) {
Thêm type hint cho giá trị trả về và param nhé.

2024-07-17 08:39 UTC, rilwis commented on src/MetaTags/Image.php
> +		$post_type_object = get_queried_object();
Chỗ này dùng cho singular, nên tên biến ko phải là `$post_type_object` nhé, mà là `$post`. Và ko dùng `get_queried_object()` nhé, dùng `$this->get_queried_object()` vì queried object có thể bị thay đổi. Xem `Context` để biết nhé.

2024-07-17 08:39 UTC, rilwis commented on src/MetaTags/Data.php
> +			$image_id = Images::get_id_from_url( $url );
Biến `$url` này là biến nào?

2024-09-11 03:58 UTC, rilwis approved these changes

2024-09-11 04:00 UTC, merged