Feat: Replace built-in link in block editor by custom link that has u…
elightup/slim-seo pull request #167
Opened 2024-11-14 05:44 UTC by doanducanh

…gc, sponsored and title attributes

2024-11-14 11:54 UTC, rilwis requested changes

2024-11-14 11:54 UTC, rilwis commented on .gitignore
> -js/link-attributes/block-editor/dist
Mình vẫn ignore thư mục `dist` chứ? Chỉ giữ `src` thôi.

2024-11-14 11:54 UTC, rilwis commented on src/LinkAttributes.php
> +		}
Cái `react-jsx-runtime` là dùng từ WP 6.5 hay 6.6 thì phải. Khi dùng `@wordpress/scripts` bản mới từ 28.x trở lên thì sẽ require cái này. A đã setup trong `package.json` là chỉ dùng bản 27.x nên ko include `react-jsx-runtime` đâu. Nên đoạn code này e bỏ đi nhé.

2024-11-15 00:49 UTC, doanducanh commented on src/LinkAttributes.php
> +		}
Cái này là e thêm chứ k có trong AIOSEO. Do mình dùng Assets::enqueue_build_js, nên nếu k enqueue riêng cái này thì bản 6.3 -> 6.5 file block-editor-link-attributes.js sẽ k load đc do thiếu react-jsx-runtime.min.js. E test kĩ vụ này rồi. Không bỏ cái này đc nếu k thì WP 6.3 -> 6.5 sẽ ko có cái custom link của mình

2024-11-15 00:51 UTC, doanducanh commented on .gitignore
> -js/link-attributes/block-editor/dist
Giờ làm gì còn folder dist trong js/link-attributes/block-editor nữa a nên e bỏ cái này

2024-11-15 01:00 UTC, doanducanh commented on src/LinkAttributes.php
> +		}
đây là danh sách 'dependencies' => array('lodash', 'react-jsx-runtime', 'wp-block-editor', 'wp-components', 'wp-compose', 'wp-data', 'wp-dom', 'wp-element', 'wp-hooks', 'wp-html-entities', 'wp-i18n', 'wp-primitives', 'wp-rich-text', 'wp-url') trong block-editor-link-attributes.asset.php khi pnpm run build. Bản 6.3 -> 6.5 thì các cái này đủ chỉ riêng cái react-jsx-runtime.js ko có nên phải enqueue thủ công a ạ. Nếu thiếu dependencies thì file sẽ k load a ạ.

2024-11-15 04:44 UTC, rilwis approved these changes

2024-11-15 04:52 UTC, rilwis approved these changes

2024-11-15 04:52 UTC, merged