Feat: Allow select and search posts as the destination (to input) in …
elightup/slim-seo pull request #174
Opened 2024-11-22 04:04 UTC by doanducanh

…redirection

2024-11-25 04:49 UTC, rilwis requested changes

2024-11-25 05:04 UTC, doanducanh commented on src/Helpers/Data.php
> +	}
e cũng thử dùng react-select rồi nhưng nó hoạt động ko ổn lắm với custom value a ạ, khi user gõ custom value thì phải di chuột chọn Create, e thử override cái Enter của nó để Enter cũng tạo đc custom value (k cần click chọn Create) nhưng nó hoạt động ko ổn định a ạ.

2024-11-25 05:05 UTC, rilwis commented on src/Helpers/Data.php
> +	}
Nếu thế thì làm UI như em làm hiện tại cũng được, nhưng nên làm ajax mỗi khi user request e ạ.

2024-11-26 02:59 UTC, doanducanh commented on src/Helpers/Data.php
> +	}
a check lại giúp e ạ

2024-11-26 07:52 UTC, rilwis approved these changes

2024-11-26 08:12 UTC, merged