add feature edit meta data in quick and bulk edit
elightup/slim-seo pull request #49
Opened 2022-07-23 13:53 UTC by nhatrangnet

2022-07-25 08:49 UTC, rilwis requested changes

2022-07-25 08:49 UTC, rilwis commented on src/MetaTags/Settings/BulkEdit.php
> +namespace SlimSEO\MetaTags\Settings;
Class này ko liên quan đến Settings nên ko để trong thư mục `Settings` nhé.

2022-07-25 08:49 UTC, rilwis commented on src/MetaTags/Settings/BulkEdit.php
> +	}
Bỏ method rỗng

2022-07-25 08:49 UTC, rilwis commented on src/MetaTags/Settings/BulkEdit.php
> +		add_action( 'manage_pages_custom_column', [ $this, 'populate_columns' ], 10, 2 );
Các cột của admin columns đã có sẵn rồi, nên ko cần làm lại.

2022-07-25 08:49 UTC, rilwis commented on src/MetaTags/Settings/BulkEdit.php
> +class BulkEdit extends Base {
Đừng extend lung tung. 2 cái này là những class khác hẳn nhau nhé.

2022-07-26 11:01 UTC, nhatrangnet commented on src/MetaTags/Settings/BulkEdit.php
> +		add_action( 'manage_pages_custom_column', [ $this, 'populate_columns' ], 10, 2 );
@rilwis nếu em bỏ 2 hook này thì nó không lấy được data nên hiện trắng như này thì sao anh ?
![Screenshot from 2022-07-26 18-00-24](https://user-images.githubusercontent.com/19669012/180990986-09eaabe4-40c3-4a93-b310-6b3f81c33b29.png)

2022-07-26 11:02 UTC, nhatrangnet commented on src/MetaTags/Settings/BulkEdit.php
> +class BulkEdit extends Base {
@rilwis tại em tính dùng hàm getData với save của class Base

2022-08-05 01:52 UTC, rilwis commented on src/MetaTags/AdminColumns/Post.php
> +		$this->object_type = 'post';
Khai báo property này

2022-08-05 01:52 UTC, rilwis commented on src/MetaTags/AdminColumns/Post.php
> +		add_action( "wp_ajax_ss_save_bulk", [ $this, 'ss_save_bulk_edit' ] );
Dùng nháy đơn

2022-08-05 01:53 UTC, rilwis commented on src/MetaTags/AdminColumns/Post.php
> +		add_action( "wp_ajax_ss_save_bulk", [ $this, 'ss_save_bulk_edit' ] );
Không prefix tên các hàm.

2022-08-05 01:53 UTC, rilwis commented on src/MetaTags/AdminColumns/Post.php
> +				echo ( ! empty( $data['noindex'] ) && $data['noindex'] == true ) ? 'Yes' : 'No';
Nên để dashicons và style màu cho nó thay vì để chữ Yes/No.

2022-08-05 02:14 UTC, rilwis commented on src/MetaTags/AdminColumns/Post.php
> +				break;
- Nên check `$column_name === 'meta_title'` ko và output cả 3 fields luôn, ko nhất thiết phải check cả 3 cái.
- Output cả giá trị đã có, hiện tại luôn luôn output value = ''

2022-08-11 02:47 UTC, merged