Auto redirect if hierarchical post slug changed
elightup/slim-seo pull request #63
Opened 2022-12-16 03:29 UTC by doanducanh

2022-12-16 06:58 UTC, rilwis requested changes

2022-12-16 06:58 UTC, rilwis commented on src/Redirection/Loader.php
> +		if ( empty( $children_posts ) ) {
Chỗ này có cần phải loop qua cả các grand-children posts ko?

2022-12-18 06:12 UTC, doanducanh commented on src/Redirection/Loader.php
> +		if ( empty( $children_posts ) ) {
có chứ a, e dùng đệ quy rồi đó a
`public static function get_children_posts( int $post_id ) : array {
		$posts          = [];
		$children_posts = get_children( [ 'post_parent' => $post_id ] );

		if ( empty( $children_posts ) ) {
			return $posts;
		}

		foreach ( $children_posts as $children_post ) {
			$posts[] = $children_post;

			$child_children_posts = self::get_children_posts( $children_post->ID );

			if ( ! empty( $child_children_posts ) ) {
				$posts = array_merge( $posts, $child_children_posts );
			}
		}

		return $posts;
	}`

2022-12-18 06:17 UTC, doanducanh commented on src/Redirection/Loader.php
> +		if ( empty( $children_posts ) ) {
e đệ quy và lưu tất cả children & grand children & grand grand .. children posts tất cả vào $children_posts rồi mới loop mà, e test kĩ đến cả page level 7 rồi, chạy ok mà a, a cứ đọc kĩ đoạn code mà xem.

2022-12-19 14:03 UTC, rilwis approved these changes

2022-12-19 14:03 UTC, merged